name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # --------------------
      # Gitleaks
      # --------------------
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      # --------------------
      # Semgrep
      # --------------------
      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
          --config=auto . \
          --json \
          --output semgrep-results.json

      # --------------------
      # Trivy
      # --------------------
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-results.json

      # --------------------
      # Checkov
      # --------------------
      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov
        continue-on-error: true
        run: |
          checkov -d . \
          -o json > checkov-results.json

      # --------------------
      # Risk Score
      # --------------------
      - name: Calculate Security Risk Score
        run: |
          python security/risk_score.py

      # --------------------
      # Upload Reports
      # --------------------
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-results.json
            trivy-results.json
            checkov-results.json