name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      # --------------------
      # Checkout Repository
      # --------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------
      # Setup Python
      # --------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # --------------------
      # Gitleaks Secret Scan
      # --------------------
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      # --------------------
      # Semgrep SAST Scan
      # --------------------
      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
          --config=auto . \
          --error \
          --json \
          --output semgrep-results.json

      # --------------------
      # Trivy Vulnerability Scan
      # --------------------
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-results.json

      # --------------------
      # Checkov IaC Scan
      # --------------------
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: sarif
          soft_fail: true
          skip_check: CKV_K8S_43

      # --------------------
      # Debug Generated Files
      # --------------------
      - name: Debug Files
        if: always()
        run: |
          echo "=== JSON Files ==="
          find . -name "*.json"

          echo "=== SARIF Files ==="
          find . -name "*.sarif"

      # --------------------
      # Risk Score Engine
      # --------------------
      - name: Calculate Security Risk Score
        run: |
          python security/risk_score.py

      # --------------------
      # Create Reports Folder
      # --------------------
      - name: Create Reports Directory
        if: always()
        run: |
          mkdir -p reports

          if [ -f semgrep-results.json ]; then
            cp semgrep-results.json reports/
          fi

          if [ -f trivy-results.json ]; then
            cp trivy-results.json reports/
          fi

          if [ -f results.sarif ]; then
            cp results.sarif reports/
          fi

      # --------------------
      # Upload Reports
      # --------------------
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
